from enum import StrEnum


class AllureTag(StrEnum):
    COURSES = 'COURSES'
    DASHBOARD = 'DASHBOARD'
    REGRESSION = 'REGRESSION'
    USER_LOGIN = 'USER_LOGIN'
    NAVIGATION = 'NAVIGATION'
    REGISTRATION = 'REGISTRATION'
    AUTHORIZATION = 'AUTHORIZATION'
